_wandb:
    value:
        cli_version: 0.22.0
        e:
            q4acpftidhigxwmngd8gmw62ijamdiqn:
                codePath: project1.ipynb
                codePathLocal: project1.ipynb
                cpu_count: 10
                cpu_count_logical: 16
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "1022782410752"
                        used: "957593833472"
                email: bizon.mimi@gmail.com
                executable: C:\Users\bizon\AppData\Local\Programs\Python\Python313\python.exe
                git:
                    commit: 607544f209610110215f9ca0336ecb59047fd599
                    remote: https://github.com/JozefBizon/AB_zneus_01.git
                gpu: NVIDIA GeForce RTX 3060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3840
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce RTX 3060 Laptop GPU
                      uuid: GPU-715a99be-6dac-763a-f39e-e2722a57ecff
                host: Bizon
                memory:
                    total: "16782184448"
                os: Windows-11-10.0.26100-SP0
                program: project1.ipynb
                python: CPython 3.13.0
                root: C:\Users\bizon\Desktop\skola\5.semester\ZNEUS\projekt1\AB_zneus_01
                startedAt: "2025-10-26T21:59:08.027674Z"
                writerId: q4acpftidhigxwmngd8gmw62ijamdiqn
        m: []
        python_version: 3.13.0
        t:
            "3":
                - 2
                - 16
            "4": 3.13.0
            "5": 0.22.0
            "8":
                - 1
                - 3
            "12": 0.22.0
            "13": windows-amd64
architecture:
    value: CNN
dataset:
    value: CIFAR-100
epochs:
    value: 10
learning_rate:
    value: 0.02
